# This is a basic workflow to help you get started with Actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy: 
      matrix: 
        python-version: [3.7.4]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.4
      uses:actions/setup-python@v2
      with:
        python-version: 3.7.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test_calculator_exercise_6.py
